[server]
enableStaticServing = true

[theme]
base = "light"

[global]
disableWatchdogWarning = true

[runner]
magicEnabled = false

[client]
showErrorDetails = true

[logger]
level = "info"

[deprecation]
showfileUploaderEncoding = false

[ui]
hideTopBar = false

[chart]
# ðŸ‘‡ LA CLÃ‰
enableAltair = false
